shadowMapResolution=4096
shadowDistance=128.0

screen=<profile> <empty> [SHADOWS] [MOTION_BLUR] [SKY] [CELESTIAL]
screen.SHADOWS=shadowMapResolution shadowDistance
screen.MOTION_BLUR=MOTION_BLUR_STRENGTH
screen.SKY=SKY_BRIGHTNESS
screen.CELESTIAL=SUN_MOON_SIZE

sliders=shadowDistance.0.0.256.0.1.0 MOTION_BLUR_STRENGTH.0.0.1.0.0.01 SKY_BRIGHTNESS.0.5.2.0.0.01 SUN_MOON_SIZE.0.5.3.0.0.1

version=1.0.8
